/* Generated By:JavaCC: Do not edit this line. EG1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int MOD = 9;
  /** RegularExpression Id. */
  int NOT = 10;
  /** RegularExpression Id. */
  int EQ = 11;
  /** RegularExpression Id. */
  int DEQ = 12;
  /** RegularExpression Id. */
  int LBRACE = 13;
  /** RegularExpression Id. */
  int RBRACE = 14;
  /** RegularExpression Id. */
  int LPAREN = 15;
  /** RegularExpression Id. */
  int RPAREN = 16;
  /** RegularExpression Id. */
  int LT = 17;
  /** RegularExpression Id. */
  int GT = 18;
  /** RegularExpression Id. */
  int QMARK = 19;
  /** RegularExpression Id. */
  int OR = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int COLON = 22;
  /** RegularExpression Id. */
  int SEMI = 23;
  /** RegularExpression Id. */
  int BREAK = 24;
  /** RegularExpression Id. */
  int CONT = 25;
  /** RegularExpression Id. */
  int ELSE = 26;
  /** RegularExpression Id. */
  int IF = 27;
  /** RegularExpression Id. */
  int RET = 28;
  /** RegularExpression Id. */
  int WHILE = 29;
  /** RegularExpression Id. */
  int LETTER = 30;
  /** RegularExpression Id. */
  int DIGIT = 31;
  /** RegularExpression Id. */
  int INT = 32;
  /** RegularExpression Id. */
  int ID = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"!\"",
    "\"=\"",
    "\"==\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\">\"",
    "\"?\"",
    "\"|\"",
    "\"&\"",
    "\":\"",
    "\";\"",
    "\"break\"",
    "\"continue\"",
    "\"else\"",
    "\"if\"",
    "\"return\"",
    "\"while\"",
    "<LETTER>",
    "<DIGIT>",
    "<INT>",
    "<ID>",
  };

}
